[611] feat: redesign of directory page
QualityUnit/postaffiliatepro-theme pull request #252
Opened 2022-10-24 19:53 UTC by Sperthix

**Changes proposed in this Pull Request**
Redesigned directory homepage.

**Testing instructions**
Go to [this](http://postaffiliatepro.local/affiliate-program-directory/) page
Check the design

**Checklist**
- [x] My code follows the style guidelines of this project
- [x] My commits follow the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

Close QualityUnit/web-issues#611

2022-10-27 07:46 UTC, jremen requested changes
Fix obvious visual bugs and fix line-height: to whole number instead of pixels (divide current px value by font size used)

![Screenshot 2022-10-27 at 09 43 20](https://user
![Screenshot 2022-10-27 at 09 41 50](https://user-images.githubusercontent.com/7055428/198222414-ec38674b-90a0-4d4d-9fb0-d25597df0beb.png)
-images.githubusercontent.com/7055428/198222390-2edf6060-2a0e-4460-849b-bed7418db04c.png)

2022-10-27 07:46 UTC, jremen commented on assets/styles/pages/Archive.scss
> +					// display: block;
Remove commented out code

2022-10-27 07:46 UTC, jremen commented on assets/styles/pages/Archive.scss
>  			line-height: 48px;
use line-height: 3 as 1rem = 16px * 3 = 48px

2022-10-27 07:46 UTC, jremen commented on assets/styles/pages/Archive.scss
>  			line-height: 48px;
line-height: 3

2022-10-27 07:46 UTC, jremen commented on assets/styles/pages/Archive.scss
>  				line-height: 28px;
line-height: 1.75

2022-11-09 06:28 UTC, mvstepanek commented
@jremen, make those item cards clickable and make padding bigger in section Affiliate program categories.

2022-11-09 08:09 UTC, jremen commented
> @jremen, make those item cards clickable and make padding bigger in section Affiliate program categories.

Done

2022-11-11 11:46 UTC, mvstepanek approved these changes

2022-11-14 05:46 UTC, merged