[907] Landing pages redesign review feedback
QualityUnit/postaffiliatepro-theme pull request #330
Opened 2022-12-29 10:11 UTC by rlaco-qualityunit

**Changes proposed in this Pull Request**
Final changes on homepage and landing pages.

**Testing instructions**
Check and test changes

**Checklist**
- [ ] My code follows the style guidelines of this project
- [ ] My commits follow the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

Close QualityUnit/web-issues#907

2023-01-02 07:28 UTC, jremen commented on assets/styles/components/_Boxes.scss
> +			@include hover() {
I would suggest to wrap :hover state in the mixin into @media (hover:hover) { &:hover} } media query

2023-01-02 07:29 UTC, jremen requested changes
Just wrap the hover mixin :hover state to media query hover:hover

2023-01-03 13:18 UTC, rlaco-qualityunit commented
> Just wrap the hover mixin :hover state to media query hover:hover

done

2023-01-09 09:05 UTC, jremen approved these changes

2023-01-09 12:40 UTC, merged