style: adjusted height of hover effect on more integrations button
QualityUnit/postaffiliatepro-theme pull request #37
Opened 2022-06-05 23:02 UTC by Sperthix

**Changes proposed in this Pull Request**
Adjusted height of hover effect on more integrations button

**Testing instructions**
Describe how and what should be tested by a Tester

**Checklist**
- [x] My code follows the style guidelines of this project
- [x] My commits follow the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-06-06 05:32 UTC, jremen approved these changes

2022-06-08 07:37 UTC, mvstepanek requested changes

2022-06-08 07:37 UTC, mvstepanek commented on assets/styles/layouts/_Header.scss
> +						height: 1.6em !important;
All items should have the same height and keep it the same on LA.

<img width="449" alt="Screenshot 2022-06-08 at 09 35 45" src="https://user-images.githubusercontent.com/17085174/172559308-28f3fcf9-2df7-44c1-99d8-053ed991a057.png">

2022-06-08 12:05 UTC, mvstepanek approved these changes

2022-06-08 12:46 UTC, merged