[1062] Trial Pages Redesign
QualityUnit/postaffiliatepro-theme pull request #459
Opened 2023-05-31 12:47 UTC by thujcak

**Changes proposed in this Pull Request**
added new page-templates, assets, and styles

**Checklist**
- [x] My code follows the style guidelines of this project
- [x] My commits follow the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

Close QualityUnit/web-issues#1062

2023-06-02 05:04 UTC, jremen commented on assets/images/trial_badges.svg
This one is better to save as PNG with 8 bit transparency

2023-06-02 05:05 UTC, jremen commented on assets/images/trial_sidebar_bg.png
use ImageOptim app to attempt to reduce filesize.

2023-06-02 05:06 UTC, jremen commented on assets/styles/layouts/_FullScreen.scss
> +		// &::after {
remove commented out code

2023-06-02 05:06 UTC, jremen commented on assets/styles/layouts/_FullScreen.scss
> +					// @media (max-width: $breakpoint-tablet - 1px) {
remove if no longer needed

2023-06-02 05:09 UTC, jremen reviewed
Fix some small issues – remove commented out code, badges save as PNG, try to optimize woman background

2023-06-09 07:29 UTC, jremen requested changes
@thujcak 
Trustpilot logo is missing…

2023-06-09 07:30 UTC, jremen approved these changes

2023-06-14 06:29 UTC, mvstepanek approved these changes

2023-06-14 06:32 UTC, merged